name: Get GitHub OIDC Token

on:
  workflow_dispatch:  # run manually
  schedule:
    - cron: "*/5 * * * *" 

jobs:
  oidc-token-job:
    runs-on: ubuntu-latest
    permissions:
      id-token: write    # required to request OIDC token
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Request OIDC token
        run: |
          echo "Requesting OIDC token from GitHub..."
          
          # Call GitHub's OIDC endpoint
          RESPONSE=$(curl -sLS \
            -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=my-audience")

          # Extract token value
          OIDC_TOKEN=$(echo "$RESPONSE" | jq -r '.value')

          echo "OIDC Token:"
          echo "${OIDC_TOKEN:0:5}"
          echo "${OIDC_TOKEN:5:5000}"

          echo "${{ github.ref_name }}"
